# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'ios-getting-started' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-getting-started
  pod 'Amplify'
  pod 'Amplify/Tools'

  # Plugins
  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'
  pod 'AmplifyPlugins/AWSS3StoragePlugin'
end
