# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

def podsInstall
  
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Firebase/Core'
  pod 'Firebase/DynamicLinks'
  pod 'SwiftGen', '~> 6.1'
  pod 'XLPagerTabStrip', :git => 'https://github.com/paduh/XLPagerTabStrip.git', :branch => 'master'
  pod 'SVProgressHUD'
  pod 'FDTake', :git => 'https://github.com/carlosmouracorreia/FDTake.git', :branch => 'master'
  pod 'Kingfisher', '~> 4.0'
  pod 'Moya', '~> 11.0'
  pod 'FSCalendar'
  pod 'Pageboy', '~> 2.6'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'IQKeyboardManagerSwift'
  pod 'PhoneNumberKit', '~> 2.5'
  pod 'AWSS3', '2.9.3'
  pod 'FacebookShare'
  pod 'Cache'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Cosmos', '~> 17.0'
  pod 'MessageKit', :git => 'https://github.com/MessageKit/MessageKit.git', :branch => '3.0.0-swift5'
  pod 'Hakawai'
  pod 'Parchment'
  pod 'DropDown'
  pod 'AHKNavigationController'
  pod 'MessageInputBar', :git => 'https://github.com/MessageKit/MessageInputBar.git', :branch => 'master'
  pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'SDWebImage', '~> 5.0'
  pod 'JPVideoPlayer'
  
end

target 'Trajilis' do
  podsInstall
  
  target 'TrajilisTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'TrajilisUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'Trajilis Staging' do
  podsInstall
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      if target.name == 'Cache'
#        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
#      end
#      if target.name == 'Alamofire'
#        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
#      end
#      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
#    end
#  end
#end
