platform :ios, "10.0"
use_frameworks!

target 'ChatChat' do
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'JSQMessagesViewController'
    pod 'SwiftGifOrigin', '~> 1.6.1'
end
